### ISSUE TITLE
关于高德地图新增旋转的功能

### ISSUE THREAD

**Issue by EwanBerg** [546669204/taobaoke#1]
请问该如何调用实现marker的角度调整呢？

**Comment by 546669204** [comment]
你在错误的地方提问了。可以在https://github.com/qiuxiang/react-native-amap3d 进行提问 
我在marker上增加了rotateAngle方法  
使用ref 获取 实例 然后 调用 rotateAngle方法   0 为正北

**Comment by EwanBerg** [comment]
抱歉。好的。谢谢您的回复。
